FROM node As build

ENV REPO_PATH=""
ENV START_PAGE=""
ENV LAST_PR=""

# install node_modules
COPY ./app /opt
WORKDIR /opt
RUN npm install

RUN mkdir /opt/app
WORKDIR /opt/app
CMD ["npm", "run", "start:file2testmap"]

